
"@context":

ontologies:
  - title: The Data Use Ontology
    preferredPrefix: DUO
    description: DUO is an ontology which represent data use conditions.
    homepage: https://github.com/EBISPOT/DUO
    annotations: null
    oboSlims: false
    preferredRootTerms: []
    uri: http://purl.obolibrary.org/obo/duo.owl
    id: duo
    mailing_list: null
    ontology_purl: http://purl.obolibrary.org/obo/duo.owl
    reasoner: NONE
    label_property: http://www.w3.org/2000/01/rdf-schema#label
    definition_property:
      - http://purl.org/dc/elements/1.1/description
    synonym_property: []
    hierarchical_property:
      - http://purl.obolibrary.org/obo/BFO_0000050
    base_uri:
      - http://purl.obolibrary.org/obo/DUO_

  - title: Adverse Event Reporting Ontology
    preferredPrefix: AERO
    description: >-
      The Adverse Event Reporting Ontology (AERO) is an ontology aimed at
      supporting clinicians at the time of data entry, increasing quality and accuracy
      of reported adverse events.
    homepage: http://purl.obolibrary.org/obo/aero
    annotations: null
    oboSlims: false
    preferredRootTerms: []
    uri: http://purl.obolibrary.org/obo/aero.owl
    id: aero
    mailing_list: null
    ontology_purl: http://purl.obolibrary.org/obo/aero.owl
    reasoner: EL
    label_property: http://www.w3.org/2000/01/rdf-schema#label
    definition_property:
      - http://purl.obolibrary.org/obo/IAO_0000115
    synonym_property:
      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
    hierarchical_property:
      - http://purl.obolibrary.org/obo/BFO_0000050
    base_uri:
      - http://purl.obolibrary.org/obo/AERO_
